app:
  mail:
    server: smtpdm.aliyun.com
    port: 465
    username: 
    password: 
    smtpauth: true
    from: 
    receive: 
    secure: ssl
  etcd:
    url: 127.0.0.1:2379
    timeout: 1s
  redis:
    addr: localhost:6379
    password: ~